import selenium
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import time


CHROME_DRIVER_PATH = YOUR_PATH
SERVICE = Service(CHROME_DRIVER_PATH)
INTERNET_SPEED_URL = "https://www.speedtest.net/"
TWITTER_URL = "https://twitter.com/home"
EMAIL = YOUR_EMAIL
PASSWORD = YOUR_PASSWORD


class InternetSpeedTitterBot:
    def __init__(self, SERVICE):
        self.driver = selenium.webdriver.Chrome(service=SERVICE)
        self.download_speed = 0
        self.upload_speed = 0

    def get_internet_speed(self):
        self.driver.get(INTERNET_SPEED_URL)
        time.sleep(5)
        go = self.driver.find_element(By.XPATH, '//*[@id="container"]/div/div[3]/div/div/div/div[2]/div[3]/div[1]/a/span[4]')
        time.sleep(5)
        go.click()
        time.sleep(60)
        download = self.driver.find_element(By.XPATH, '//*[@id="container"]/div/div[3]/div/div/div/div[2]/div[3]/div[3]/div/div[3]/div/div/div[2]/div[1]/div[2]/div/div[2]/span')
        self.download_speed = download.text
        upload = self.driver.find_element(By.XPATH, '//*[@id="container"]/div/div[3]/div/div/div/div[2]/div[3]/div[3]/div/div[3]/div/div/div[2]/div[1]/div[3]/div/div[2]/span')
        self.upload_speed = upload.text
        print(self.download_speed)
        print(self.upload_speed)

    def tweet_at_provider(self):
        self.driver.get(TWITTER_URL)
        time.sleep(5)
        email = self.driver.find_element(By.XPATH, '//*[@id="layers"]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/div[5]/label/div/div[2]/div/input')
        time.sleep(5)
        email.send_keys(EMAIL)
        time.sleep(1)
        next = self.driver.find_element(By.XPATH, '//*[@id="layers"]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/div[6]/div')
        time.sleep(1)
        next.click()
        time.sleep(5)
        password = self.driver.find_element(By.XPATH, '//*[@id="layers"]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div[1]/div/div/div[3]/div/label/div/div[2]/div[1]/input')
        password.send_keys(PASSWORD)
        login = self.driver.find_element(By.XPATH, '//*[@id="layers"]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div[2]/div/div[1]/div/div/div')
        login.click()
        time.sleep(15)
        tweet = self.driver.find_element(By.XPATH, '//*[@id="react-root"]/div/div/div[2]/main/div/div/div/div[1]/div/div[2]/div/div[2]/div[1]/div/div/div/div[2]/div[1]/div/div/div/div/div/div/div/div/div/label/div[1]/div/div/div/div/div[2]/div/div/div/div/span/br')
        tweet.send_keys(f"Hi this is a tweet generated by a Python bot: My internet Download speed is {self.download_speed}Mbps and Upload speed is {self.upload_speed}Mbps.")
        time.sleep(3)
        send = self.driver.find_element(By.XPATH, '//*[@id="react-root"]/div/div/div[2]/main/div/div/div/div[1]/div/div[2]/div/div[2]/div[1]/div/div/div/div[2]/div[3]/div/div/div[2]/div[3]/div/span/span')
        send.click()


bot = InternetSpeedTitterBot(SERVICE)
bot.get_internet_speed()
bot.tweet_at_provider()
